"""Corrigindo atrr cross_reference para nullable

Revision ID: 1c6275388401
Revises: 8ba533ecc14a
Create Date: 2025-03-20 17:07:11.883283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c6275388401'
down_revision = '8ba533ecc14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('cross_reference',
               existing_type=mysql.VARCHAR(length=2500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('cross_reference',
               existing_type=mysql.VARCHAR(length=2500),
               nullable=False)

    # ### end Alembic commands ###
