"""Permitindo start_year ser nulo

Revision ID: 2210922e90dc
Revises: e2643e6783e5
Create Date: 2025-05-29 14:18:37.113598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2210922e90dc'
down_revision = 'e2643e6783e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('start_year',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('start_year',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)

    # ### end Alembic commands ###
