"""Criando tabelas de vitrine customizada

Revision ID: 2308915fdc25
Revises: 285f1f6c7052
Create Date: 2025-07-02 15:24:23.641053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2308915fdc25'
down_revision = '285f1f6c7052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id_seller', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_seller'], ['seller.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name', 'id_seller')
    )
    op.create_table('custom_showcase',
    sa.Column('cod_product', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cod_product'], ['product.cod_product'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['name'], ['label.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cod_product', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_showcase')
    op.drop_table('label')
    # ### end Alembic commands ###
