"""nova coluna OEM na tabela de produtos

Revision ID: 23a0f01f68b4
Revises: 8f9e27049928
Create Date: 2025-09-19 14:04:11.087333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23a0f01f68b4'
down_revision = '8f9e27049928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_manufacturer',
    sa.Column('id_seller', sa.Integer(), nullable=False),
    sa.Column('id_manufacturer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_seller', 'id_manufacturer')
    )
    op.create_table('user_seller',
    sa.Column('id_seller', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_seller'], ['seller.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_seller', 'id_user')
    )
    op.drop_table('seller_users')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oem', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('id_manufacturer', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'manufacturer', ['id_manufacturer'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_domain', mysql.VARCHAR(length=15), nullable=False))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_manufacturer')
        batch_op.drop_column('oem')

    op.create_table('seller_users',
    sa.Column('id_seller', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_seller'], ['seller.id'], name='seller_users_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='seller_users_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_seller', 'id_user'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_seller')
    op.drop_table('seller_manufacturer')
    op.drop_table('manufacturer')
    # ### end Alembic commands ###
