"""Criando relação entre seller e vehicle brands, e seller e vehicle

Revision ID: 5023b7616b3f
Revises: 2210922e90dc
Create Date: 2025-06-03 11:22:06.764064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5023b7616b3f'
down_revision = '2210922e90dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_brands',
    sa.Column('id_seller', sa.Integer(), nullable=False),
    sa.Column('hash_brand', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['hash_brand'], ['vehicle_brand.hash_brand'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['id_seller'], ['seller.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_seller', 'hash_brand')
    )
    op.create_table('seller_vehicles',
    sa.Column('id_seller', sa.Integer(), nullable=False),
    sa.Column('vehicle_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_seller'], ['seller.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_name'], ['vehicle.vehicle_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_seller', 'vehicle_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_vehicles')
    op.drop_table('seller_brands')
    # ### end Alembic commands ###
