"""Criando tabela de marcas de veículos

Revision ID: 5b91f29741ea
Revises: f6efc5fa7850
Create Date: 2025-04-02 14:38:51.187131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b91f29741ea'
down_revision = 'f6efc5fa7850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_brand',
    sa.Column('hash_brand', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('brand_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('hash_brand')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_brand', sa.String(length=255), nullable=False))
        batch_op.create_foreign_key(None, 'vehicle_brand', ['hash_brand'], ['hash_brand'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hash_brand')

    op.drop_table('vehicle_brand')
    # ### end Alembic commands ###
