"""Criando tabela intermediária entre seller e vehicles

Revision ID: 6c02bc55f994
Revises: 2210922e90dc
Create Date: 2025-06-02 16:26:45.985913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c02bc55f994'
down_revision = '2210922e90dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_vehicles',
    sa.Column('id_seller', sa.Integer(), nullable=False),
    sa.Column('vehicle_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_seller'], ['seller.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_name'], ['vehicle.vehicle_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_seller', 'vehicle_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_vehicles')
    # ### end Alembic commands ###
