"""Corrigindo atrr end_year para nullable

Revision ID: 6ff94455117c
Revises: d5ff9d87de42
Create Date: 2025-03-20 16:33:57.655974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ff94455117c'
down_revision = 'd5ff9d87de42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('end_year',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('end_year',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)

    # ### end Alembic commands ###
