"""Adicionando Cascade quando atualizar ou deletar registros

Revision ID: 7c3c19335a27
Revises: a7f177558af9
Create Date: 2025-06-05 15:10:58.987757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3c19335a27'
down_revision = 'a7f177558af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compatibility', schema=None) as batch_op:
        batch_op.drop_constraint('compatibility_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('compatibility_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_name'], ['vehicle_name'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'product', ['cod_product'], ['cod_product'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['hash_category'], ['hash_category'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('seller_brands', schema=None) as batch_op:
        batch_op.drop_constraint('seller_brands_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle_brand', ['hash_brand'], ['hash_brand'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('seller_categories', schema=None) as batch_op:
        batch_op.drop_constraint('seller_categories_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['hash_category'], ['hash_category'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('vehicle_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle_brand', ['hash_brand'], ['hash_brand'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('vehicle_ibfk_1', 'vehicle_brand', ['hash_brand'], ['hash_brand'], onupdate='CASCADE')

    with op.batch_alter_table('seller_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('seller_categories_ibfk_1', 'category', ['hash_category'], ['hash_category'], onupdate='CASCADE')

    with op.batch_alter_table('seller_brands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('seller_brands_ibfk_1', 'vehicle_brand', ['hash_brand'], ['hash_brand'], onupdate='CASCADE')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_ibfk_1', 'category', ['hash_category'], ['hash_category'], onupdate='CASCADE')

    with op.batch_alter_table('compatibility', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('compatibility_ibfk_1', 'product', ['cod_product'], ['cod_product'], onupdate='CASCADE')
        batch_op.create_foreign_key('compatibility_ibfk_2', 'vehicle', ['vehicle_name'], ['vehicle_name'], onupdate='CASCADE')

    # ### end Alembic commands ###
