"""Corrigindo atrr gear_dimensions

Revision ID: 7eb57d60fcdf
Revises: e13197415a6c
Create Date: 2025-03-20 15:06:28.414460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7eb57d60fcdf'
down_revision = 'e13197415a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gear_dimensions', sa.String(length=255), nullable=False))
        batch_op.drop_column('gear_dimenions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gear_dimenions', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('gear_dimensions')

    # ### end Alembic commands ###
