"""Adicionando referência de domínio de seller

Revision ID: 82cf421964e3
Revises: 8f9e27049928
Create Date: 2025-08-04 15:44:00.333360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cf421964e3'
down_revision = '8f9e27049928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_domain', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_column('seller_domain')

    # ### end Alembic commands ###
