"""Corrigindo quantidade máxima de chars em cross_reference

Revision ID: 8ba533ecc14a
Revises: 6ff94455117c
Create Date: 2025-03-20 16:43:08.825469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ba533ecc14a'
down_revision = '6ff94455117c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('cross_reference',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=2500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('cross_reference',
               existing_type=sa.String(length=2500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
