"""Criando relacionamento entre seller e category

Revision ID: a7f177558af9
Revises: 5023b7616b3f
Create Date: 2025-06-03 14:49:13.453648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f177558af9'
down_revision = '5023b7616b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_categories',
    sa.Column('id_seller', sa.Integer(), nullable=False),
    sa.Column('hash_category', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['hash_category'], ['category.hash_category'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['id_seller'], ['seller.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_seller', 'hash_category')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_categories')
    # ### end Alembic commands ###
