"""Adicionando informações empresariais em usuário para inbound

Revision ID: c2434a272ab2
Revises: abbd98dce565
Create Date: 2025-04-07 14:50:50.919863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2434a272ab2'
down_revision = 'abbd98dce565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###
