"""Permitindo bar_code ser nulo

Revision ID: cb4f6b0756d9
Revises: e79fed0db0ae
Create Date: 2025-05-29 14:00:46.242747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb4f6b0756d9'
down_revision = 'e79fed0db0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('bar_code',
               existing_type=mysql.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('bar_code',
               existing_type=mysql.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
