"""Migration inicial

Revision ID: e13197415a6c
Revises: 
Create Date: 2025-03-19 17:28:50.635987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13197415a6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('hash_category', sa.String(length=255), nullable=False),
    sa.Column('name_category', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('hash_category')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_name', sa.String(length=255), nullable=False),
    sa.Column('start_year', sa.String(length=4), nullable=False),
    sa.Column('end_year', sa.String(length=4), nullable=False),
    sa.Column('vehicle_type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_name')
    )
    op.create_table('product',
    sa.Column('cod_product', sa.String(length=255), nullable=False),
    sa.Column('name_product', sa.String(length=255), nullable=False),
    sa.Column('bar_code', sa.BigInteger(), nullable=False),
    sa.Column('gear_quantity', sa.Integer(), nullable=False),
    sa.Column('gear_dimenions', sa.String(length=255), nullable=False),
    sa.Column('cross_reference', sa.String(length=255), nullable=False),
    sa.Column('hash_category', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['hash_category'], ['category.hash_category'], ),
    sa.PrimaryKeyConstraint('cod_product')
    )
    op.create_table('compatibility',
    sa.Column('cod_product', sa.String(length=255), nullable=False),
    sa.Column('vehicle_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cod_product'], ['product.cod_product'], ),
    sa.ForeignKeyConstraint(['vehicle_name'], ['vehicle.vehicle_name'], ),
    sa.PrimaryKeyConstraint('cod_product', 'vehicle_name')
    )
    op.create_table('images',
    sa.Column('cod_product', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cod_product'], ['product.cod_product'], ),
    sa.PrimaryKeyConstraint('cod_product')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('compatibility')
    op.drop_table('product')
    op.drop_table('vehicle')
    op.drop_table('category')
    # ### end Alembic commands ###
