"""Permitindo gear_quantity ser nulo

Revision ID: e2643e6783e5
Revises: cb4f6b0756d9
Create Date: 2025-05-29 14:03:30.366738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2643e6783e5'
down_revision = 'cb4f6b0756d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('gear_quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('gear_quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
