"""Relacionamento entre produtos e seller

Revision ID: e79fed0db0ae
Revises: 6e9c5471a4b8
Create Date: 2025-05-29 13:12:43.437344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79fed0db0ae'
down_revision = '6e9c5471a4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_seller', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'seller', ['id_seller'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_seller')

    # ### end Alembic commands ###
