"""Criando propriedade display_order

Revision ID: ec5e312a0b53
Revises: ed1ab20b9e6a
Create Date: 2025-04-14 09:35:30.278188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5e312a0b53'
down_revision = 'ed1ab20b9e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False))

    with op.batch_alter_table('vehicle_brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_brand', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
