"""Adicionando on cascade para todos updates de chaves estrangeiras

Revision ID: ed1ab20b9e6a
Revises: c2434a272ab2
Create Date: 2025-04-11 14:30:50.920800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1ab20b9e6a'
down_revision = 'c2434a272ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compatibility', schema=None) as batch_op:
        batch_op.drop_constraint('compatibility_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('compatibility_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['cod_product'], ['cod_product'], onupdate='CASCADE')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_name'], ['vehicle_name'], onupdate='CASCADE')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint('images_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['cod_product'], ['cod_product'], onupdate='CASCADE')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['hash_category'], ['hash_category'], onupdate='CASCADE')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('vehicle_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle_brand', ['hash_brand'], ['hash_brand'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('vehicle_ibfk_1', 'vehicle_brand', ['hash_brand'], ['hash_brand'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_ibfk_1', 'category', ['hash_category'], ['hash_category'])

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('images_ibfk_1', 'product', ['cod_product'], ['cod_product'])

    with op.batch_alter_table('compatibility', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('compatibility_ibfk_2', 'vehicle', ['vehicle_name'], ['vehicle_name'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key('compatibility_ibfk_1', 'product', ['cod_product'], ['cod_product'])

    # ### end Alembic commands ###
