"""Criando relação entre seller e vehicle brands

Revision ID: f4a33316da80
Revises: 6c02bc55f994
Create Date: 2025-06-03 09:26:47.812577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a33316da80'
down_revision = '6c02bc55f994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_brands',
    sa.Column('id_seller', sa.Integer(), nullable=False),
    sa.Column('hash_brand', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['hash_brand'], ['vehicle_brand.hash_brand'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['id_seller'], ['seller.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_seller')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_brands')
    # ### end Alembic commands ###
