"""Chave primária de imagem em hash

Revision ID: f6efc5fa7850
Revises: 1c6275388401
Create Date: 2025-03-24 15:46:33.810914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6efc5fa7850'
down_revision = '1c6275388401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_image', sa.String(length=255), nullable=False))
        batch_op.alter_column('cod_product',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('cod_product',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('id_image')

    # ### end Alembic commands ###
